name: My_check

on:
  - push
  - pull_request

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      
      - name: Install poetry
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry

      - name: Install and check lint 
        run: |
          make install
          make lint
  
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.12
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - uses: paambaati/codeclimate-action@master
      env:
        CC_TEST_REPORTER_ID: 5bafefc381d19d325eb95d6e35c3387ba7d66814dfbe8ca026d59d72f9d0715b
      with:
        coverageCommand: yarn coverage
