name: My_check

on:
  - push
  - pull_request

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pavelkoA/python-project-50@main
      - run: make-install
      - run: make-lint
      
