name: My_check

on:
  - push
  - pull_request

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      maxrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          make install

      - name: Install and check lint
        run: make lint

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
